### ISSUE TITLE
Внести доработки в компоненты на основе изменений в гайдах

### ISSUE THREAD

**Issue by MaratKhaid** [sima-land/ui-nucleons#275]
#### Ситуация

Гайды на ProductCarousel снова изменились

#### Необходимо

- Hint: по умолчанию сделатьь скрытие временного хинта через 3 сек, добавить возможность менять этот таймаут
- TopBar: добавить возможность выводить сложный заголовок, например со ссылками, жирным текстом, курсивом и тд

**Comment by krutoo** [comment]
по топ бару уже сделано
по хинту сделано в рамках задачи https://github.com/sima-land/ui-nucleons/issues/270 и появится в ближайшем релизе
