### ISSUE TITLE
При обновлении зависимостей вылетает ошибка

### ISSUE THREAD

**Issue by rychkovwork** [sima-land/ui-nucleons#278]
![image](https://github.com/sima-land/ui-nucleons/assets/136083796/5bb03fdd-fdb3-41fc-b76c-796625990ae6)

**Comment by krutoo** [comment]
с какой на какую версию библиотеки происходит обновление?

**Comment by rychkovwork** [comment]
Не так выразился - при переустановке зависимостей вылетело(удалял node_modules, package-lock.json, после заново устанавливал), имеется ли решение данной проблемы?

**Comment by rychkovwork** [comment]
да я вот смотрю, в целом как была 45.0.0-alpha.3 так и осталась, но ошибки летят
 
 
--
Владислав Рычков
Отправлено из Почты  Mail.ru

**Comment by krutoo** [comment]
если версия библиотеки не менялась то судя по всему это проблема не библиотеки а проекта

**Comment by rychkovwork** [comment]
можно закрывать, через yarn получилось, почему-то, через npm не выходило
