### ISSUE TITLE
Pagination: обновить в соответствии с измененными дизайн-гайдами

### ISSUE THREAD

**Issue by MaratKhaid** [sima-land/ui-nucleons#284]
#### Ситуация

гайд компонента Pagination был изменен

#### Необходимо

изменить компонент Pagination, учитывая новую логику:

- возможность вывода четырехзначных чисел
- максимум 7 кнопок страниц
- возможность скрытия кнопок-стрелок
- disabled для кнопок-стрелок

**Comment by krutoo** [comment]
Нужно будет сделать компонент Pagination таким чтобы ему можно было задать механизм определения страниц в виде функции

по умолчанию механизм будет не основе гайдов

также можно избавиться от BasePagination чтобы упростить логику
