### ISSUE TITLE
Autocomplete: не прокручивается выпадающий список внутри Modal

### ISSUE THREAD

**Issue by katrinZu** [sima-land/ui-nucleons#288]
В мобильной версии тачем айтемы в выпадающем списке скроллится только за ползунок.

Необходимо доработать возможность скроллить айтемы при взаимодействии со всем списком.

**Comment by krutoo** [comment]
Исправлено здесь:
https://github.com/sima-land/ui-nucleons/pull/370

Теперь для корректной работы нужно прокинуть BSL_IGNORE_ATTR в viewportProps в Dropdown

Компоненты Autocomplete, Select, PhoneInput позволяют это сделать
