### ISSUE TITLE
Dropdown: доработать в соответствии с новыми дизайн-гайдами

### ISSUE THREAD

**Issue by MaratKhaid** [sima-land/ui-nucleons#355]
**Ситуация**

Гайды для dropdown обновили и теперь дропдаун закрывается при скролле вне его. Также изменения внесли в гайд автокомплита и селекта

**Необходимо**

доработать компонент так чтобы дропдаун скрывался при скролле вне его

**Comment by krutoo** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event

**Comment by krutoo** [comment]
Можно решить так:

```js
document.addEventListener('scroll', () => {
  console.count('document:scroll')
}, true)
```

Но это повлечет сложности на маленьких экранах

**Comment by krutoo** [comment]
Решили скрывать только при прокрутке колесом для того чтобы сохранить возможность прокрутки на мобильных устройствах touch'ем
